name: Pull Request checks

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/build.yml
  small-test:
    needs:
      - build
    uses: ./.github/workflows/test-small.yml
  medium-test:
    needs:
      - small-test
    uses: ./.github/workflows/test-medium.yml